---

#--------------------------Repository settings---------------------------------

- name: Disable pve-enterprise repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/pve-enterprise.sources
    content: |
      Types: deb
      URIs: https://enterprise.proxmox.com/debian/pve
      Suites: trixie
      Components: pve-enterprise
      Signed-By: /usr/share/keyrings/proxmox-archive-keyring.gpg
      Enabled: false

- name: Disable repository ceph
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/ceph.sources
    content: |
      Types: deb
      URIs: https://enterprise.proxmox.com/debian/ceph-squid
      Suites: trixie
      Components: enterprise
      Signed-By: /usr/share/keyrings/proxmox-archive-keyring.gpg
      Enabled: false

- name: Add pve-no-subscription repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/proxmox.sources
    content: |
      Types: deb
      URIs: http://download.proxmox.com/debian/pve
      Suites: trixie
      Components: pve-no-subscription
      Signed-By: /usr/share/keyrings/proxmox-archive-keyring.gpg
      Enabled: true

#-----------------------Set timezone----------------------------------

- name: Set timezone
  community.general.timezone:
    name: Europe/Moscow

#--------------------------Updates------------------------------------------------

- name: Update and upgrade
  ansible.builtin.apt:
    name: '*'
    state: latest
    update_cache: yes

- name: System update via cron
  cron:
    name: "APT update and cleanup"
    minute: "20"
    hour: "6"
    job: >
      apt update &&
      apt upgrade -y &&
      apt autoremove -y &&
      apt autoclean -y

#-----------------------Install packages----------------------------------

- name: Install apt packages
  ansible.builtin.apt:
    name:
      - neovim
      - cron
      - zip
      - unzip
      - htop
      - libguestfs-tools
    state: latest

- name: Install sops binary
  get_url:
    url: https://github.com/getsops/sops/releases/download/v3.12.2/sops-v3.12.2.linux.amd64
    dest: /usr/local/bin/sops
    mode: '0755'
    owner: root
    group: root

#--------------------------Network settings----------------------------------

- name: Copy interfaces file
  ansible.builtin.copy:
    src: files/interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'

- name: Apply settings
  ansible.builtin.command:
    cmd: ifreload -a

#--------------------------SSH settings----------------------------------

- name: Copy control ssh key
  ansible.builtin.copy:
    src: authorized_keys2
    dest: /root/.ssh/
    owner: root
    group: root
    mode: '0600'

- name: Copy sshd config
  ansible.builtin.copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'

- name: Restart sshd service
  ansible.builtin.systemd_service:
    state: restarted
    name: sshd

#--------------------------Firewall rules----------------------------------

- name: Decrypt locally
  ansible.builtin.set_fact:
    fw_content: "{{ lookup('pipe', 'sops -d /var/lib/jenkins/jobs/pve/workspace/ansible/roles/pve/config_soft/files/cluster.fw.enc') }}"
  delegate_to: localhost
  no_log: true

- name: Write to pmxcfs
  ansible.builtin.shell: cat > /etc/pve/firewall/cluster.fw
  args:
    stdin: "{{ fw_content | replace('\r\n', '\n') }}"
  become: true
  delegate_to: pve
  no_log: true

#- name: Copy rules to target
#  ansible.builtin.copy:
#    dest: /etc/pve/firewall/cluster.fw
#    owner: root
#    group: www-data
#    mode: '0640'
#    content: "{{ lookup('pipe', 'sops -d /var/lib/jenkins/jobs/pve/workspace/ansible/roles/pve/config_soft/files/cluster.fw.enc') }}"
#    unsafe_writes: true
#  delegate_to: pve

- name: Convert to ASCII
  ansible.builtin.shell: >
    sed -i 's/\r//' /etc/pve/firewall/cluster.fw
  delegate_to: pve

#-----------------------Change root password----------------------------------

- name: Change root password
  ansible.builtin.user:
    name: root
    password: '$6$Ogv7SOQr$ovSFzkn3VEkPC58NEDL91wBA3rmNTSYjGKVwmFwtVryF78hP.I5vKobSmCUr.7YKw31KRE/Swv03BUys.hNW3.'
    # python3 -c "import crypt; print(crypt.crypt('pass', crypt.mksalt(crypt.METHOD_SHA512)))"

#-----------------------Download latest debian 13 lxc image----------------------------------

- name: Update pve lxc repo
  shell: >
    pveam update

- name: Download latest lxc image
  shell: >
    pveam download local $(pveam available | awk '/debian-13-standard/ {print $2}' | sort -V | tail -1)

#-----------------------Add media-vg as storage----------------------------------

#- name: Get storage list
#  command: pvesm status --enabled 1
#  register: storage_list
#  changed_when: false
#
#- name: Add media-vg storage if missing
#  command: >
#    pvesm add lvm media-vg
#    --vgname media_vg
#    --content images
#  when: storage_list.stdout is not search("media-vg")