[global]
keyboard = "en-us"
country = "ru"
fqdn = "pve.karazhan.local"
mailto = "heimcbk201@gmail.com"
timezone = "Europe/Moscow"
root-password = "12345678"
root-ssh-keys = []

[network]
source = "from-answer"
cidr = "192.168.2.2/24"
dns = "192.168.2.1"
gateway = "192.168.2.1"
filter.ID_NET_NAME_MAC = "*"

[disk-setup]
filesystem = "ext4"
lvm.swapsize = 0
lvm.maxroot = 50
disk-list = ["/dev/nvme0n1"]

[first-boot]
source = "from-url"
ordering = "network-online"
url = "https://raw.githubusercontent.com/mishgun64/pve/refs/heads/main/pxe/first_boot.sh"
