---
#-----------------------------------------User settings---------------------------------------------

- name: Set shell for docker user
  ansible.builtin.user:
    name: docker
    shell: /bin/bash

#------------------------------------------Check directory------------------------------------------

- name: Check config directory
  ansible.builtin.stat:
    path: /home/docker/config
  register: valheim_config_dir

#------------------------------------------Generate timestamp------------------------------------------

- name: Set timestamp
  ansible.builtin.set_fact:
    backup_ts: "{{ ansible_facts['date_time']['year'] }}.{{ ansible_facts['date_time']['month'] }}.{{ ansible_facts['date_time']['day'] }}_{{ ansible_facts['date_time']['hour'] }}.{{ ansible_facts['date_time']['minute'] }}.{{ ansible_facts['date_time']['second'] }}"
  when: valheim_config_dir.stat.exists

#------------------------------------------Create backup dir------------------------------------------

- name: Create backup directory on Woodpecker
  ansible.builtin.file:
    path: /srv/backups/valheim
    state: directory
    mode: '0755'
  delegate_to: localhost
  when: valheim_config_dir.stat.exists

#------------------------------------------Stop container------------------------------------------

- name: Stop docker compose
  ansible.builtin.shell: docker compose down
  args:
    chdir: /home/docker
  when: valheim_config_dir.stat.exists

#------------------------------------------Archive------------------------------------------

- name: Archive Valheim config
  ansible.builtin.archive:
    path: /home/docker/config
    dest: "/home/docker/valheim_{{ backup_ts }}.tar.gz"
    format: gz
  when: valheim_config_dir.stat.exists

#------------------------------------------Start container------------------------------------------

- name: Start docker compose as docker user
  ansible.builtin.shell: |
    su - docker -c 'cd /home/docker && docker compose up -d'
  when: valheim_config_dir.stat.exists

#------------------------------------------Fetch------------------------------------------

- name: Fetch backup to Woodpecker
  ansible.builtin.fetch:
    src: "/home/docker/valheim_{{ backup_ts }}.tar.gz"
    dest: /srv/backups/valheim/
    flat: true
  when: valheim_config_dir.stat.exists

#------------------------------------------Cleanup------------------------------------------

- name: Cleanup remote files
  ansible.builtin.file:
    path: "/home/docker/valheim_{{ backup_ts }}.tar.gz"
    state: absent
  when: valheim_config_dir.stat.exists