services:
  pvpgn:
    image: wwmoraes/pvpgn-server:latest-sqlite3
    container_name: pvpgn-server
    restart: unless-stopped
    ports:
      - "6112:6112/tcp"   # Battle.net (основной порт)
      - "6112:6112/udp"   # Battle.net UDP
      - "6200:6200/udp"   # W3 route
    environment:
      PUID: 1001
      PGID: 1001
      TZ: Europe/Moscow
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./pvpgn_conf:/etc/pvpgn    # конфиги
      - ./pvpgn_var:/var/pvpgn      # логи, сохранения