---

#--------------------------Find backup----------------------------------

- name: Find latest backup
  delegate_to: localhost
  run_once: true
  ansible.builtin.shell: |
    ls -1t /srv/backups/pvpgn/pvpgn_*.tar.gz 2>/dev/null | head -n 1 || true
  register: latest_backup

- name: Set fact
  set_fact:
    backup_exists: "{{ latest_backup.stdout | length > 0 }}"

#--------------------------Stop container----------------------------------

- name: Stop docker compose
  ansible.builtin.shell: docker compose down
  args:
    chdir: /home/docker
  when: backup_exists

#--------------------------Extract----------------------------------

- name: Extract backup
  ansible.builtin.unarchive:
    src: "/srv/backups/pvpgn/{{ (latest_backup.stdout | basename) }}"
    dest: /home/docker/
    remote_src: false
  when: backup_exists

#--------------------------Start container----------------------------------

- name: Start PVPGN
  ansible.builtin.shell: docker compose up -d
  args:
    chdir: /home/docker
  become: true
  become_method: su
  become_user: docker