[global]
keyboard = "en-us"
country = "ru"
fqdn = "pve.karazhan.local"
mailto = "heimcbk201@gmail.com"
timezone = "Europe/Moscow"
root-password = "1234"
root-ssh-keys = []

[network]
#source = "from-dhcp"
source = "from-answer"
cidr = "192.168.1.100/24"
dns = "192.168.1.1"
gateway = "192.168.1.1"
filter.ID_NET_NAME_MAC = "*"

[disk-setup]
filesystem = "ext4"
disk-list = ["/dev/nvme0n1"]

#[first-boot]
#source = "from-url"
#ordering = "network-online"
#url = "http://192.168.1.200:8080/generic-webhook-trigger/invoke?token=proxmox-init"
