services:
  openfire:
    image: nasqueron/openfire:latest
    container_name: openfire
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/openfire
    ports:
      - "5222:5222"   # c2s (клиент-сервер)
      - "7443:7443"   # HTTP binding / BOSH
      - "9090:9090"   # веб-админка (локально)
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Moscow
    security_opt:
      - no-new-privileges:true