---

- name: Create docker group
  ansible.builtin.group:
    name: docker
    gid: 1000
    state: present

- name: Create docker user
  ansible.builtin.user:
    name: docker
    uid: 1000
    group: docker
    create_home: yes
    shell: /usr/sbin/nologin
    system: no

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install required packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create apt keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Ensure Docker GPG key is readable
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add Docker repository (docker.sources)
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.sources
    mode: "0644"
    content: |
      Types: deb
      URIs: https://download.docker.com/linux/debian
      Suites: {{ ansible_distribution_release }}
      Components: stable
      Signed-By: /etc/apt/keyrings/docker.asc

- name: Update apt cache after adding repo
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

