---

- name: Get root token
  ansible.builtin.shell: pveum user token add root@pam tf --privsep 0 | grep value | awk '{print $4}' | head -n2 | tail -n1
  register: api_token

- name: Ensure terraform secrets directory exists
  ansible.builtin.file:
    path: ../terraform/secrets
    state: directory
    mode: 0700
  delegate_to: localhost

- name: Create api file on localhost
  ansible.builtin.copy:
    mode: 0700
    dest: ../terraform/secrets/api_key
    content: '{{ api_token.stdout }}'
  when: api_token.stdout != ""
  delegate_to: localhost

- name: Trigger Jenkins webhook
  uri:
    url: "http://192.168.2.200:8080/generic-webhook-trigger/invoke?token=pve-webhook"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      event: cloud-init