---

#-----------------------User settings----------------------------------

- name: Change root password
  ansible.builtin.user:
    name: root
    password: '$6$ES3euQTVkhNu9lVN$OB5LedrbKJVnNpReELcrDpkHsERSF1iIgy9ITLpl.9q5I4K6gvwKQjTs5HkLh/P4TRatj3Fgx770P4LCEGal4.'
    # python3 -c "import crypt; print(crypt.crypt('pass', crypt.mksalt(crypt.METHOD_SHA512)))"

- name: Set shell for docker user
  user:
    name: docker
    shell: /bin/bash

#--------------------------Firewall rules----------------------------------

- name: Decrypt rules on ansible host
  ansible.builtin.shell: >
    sops -d --input-type binary --output-type binary
    /var/lib/jenkins/jobs/pve/workspace/ansible/roles/traefik/config/files/143.fw.enc >
    /var/lib/jenkins/jobs/pve/workspace/ansible/roles/traefik/config/files/143.fw
  delegate_to: localhost

- name: Copy rules to target
  ansible.builtin.copy:
    src: 143.fw
    dest: /etc/pve/firewall/143.fw
    owner: root
    group: www-data
    mode: '0640'

- name: Remove decrypted rules from ansible host
  ansible.builtin.file:
    path: /var/lib/jenkins/jobs/pve/workspace/ansible/roles/traefik/config/files/143.fw
    state: absent
  delegate_to: localhost

- name: Update firewall rules
  shell: >
    pve-firewall compile

#-----------------------Copy config files----------------------------------

- name: Copy traefik directory
  copy:
    src: traefik/
    dest: /home/docker/traefik/
    owner: docker
    group: docker
    mode: '0755'

- name: Create acme.json
  ansible.builtin.file:
    path: /home/docker/traefik/acme.json
    state: touch
    owner: docker
    group: docker
    mode: '0600'

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /home/docker/docker-compose.yml
    owner: docker
    group: docker
    mode: '0644'

#--------------------------Run container----------------------------------

- name: Pull docker compose
  ansible.builtin.shell: docker compose pull
  args:
    chdir: /home/docker
  become: true
  become_method: su
  become_user: docker
  timeout: 600

- name: Start docker compose
  ansible.builtin.shell: docker compose up -d
  args:
    chdir: /home/docker
  become: true
  become_method: su
  become_user: docker