---

#-----------------------User settings----------------------------------

- name: Change root password
  ansible.builtin.user:
    name: root
    password: '$6$ES3euQTVkhNu9lVN$OB5LedrbKJVnNpReELcrDpkHsERSF1iIgy9ITLpl.9q5I4K6gvwKQjTs5HkLh/P4TRatj3Fgx770P4LCEGal4.'
    # python3 -c "import crypt; print(crypt.crypt('pass', crypt.mksalt(crypt.METHOD_SHA512)))"

- name: Set shell for docker user
  user:
    name: docker
    shell: /bin/bash

#--------------------------Firewall rules----------------------------------

- name: Decrypt locally
  ansible.builtin.set_fact:
    fw_content: "{{ lookup('pipe', 'sops -d /var/lib/jenkins/jobs/pve/workspace/ansible/roles/traefik/config/files/143.fw.enc') }}"
  delegate_to: localhost
  no_log: true

- name: Write to pmxcfs
  ansible.builtin.shell: cat > /etc/pve/firewall/143.fw
  args:
    stdin: "{{ fw_content | replace('\r\n', '\n') }}"
  become: true
  delegate_to: pve
  no_log: true

- name: Convert to ASCII
  ansible.builtin.shell: >
    sed -i 's/\r//' /etc/pve/firewall/143.fw
  delegate_to: pve
#-----------------------Copy config files----------------------------------

- name: Copy traefik directory
  copy:
    src: traefik/
    dest: /home/docker/traefik/
    owner: docker
    group: docker
    mode: '0755'

- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: docker
    group: docker
    mode: '0755'
  loop:
    - /home/docker/traefik/logs
    - /home/docker/crowdsec/data
    - /home/docker/crowdsec/config
    - /home/docker/acme-dns/config
    - /home/docker/acme-dns/data
    - /home/docker/dumped-certs

- name: Copy acquis.yaml
  copy:
    src: crowdsec/acquis.yaml
    dest: /home/docker/crowdsec/acquis.yaml
    owner: docker
    group: docker
    mode: '0644'

- name: Create acme.json
  ansible.builtin.file:
    path: /home/docker/traefik/acme.json
    state: touch
    owner: docker
    group: docker
    mode: '0600'

#- name: Create acme.json with correct permissions
#  ansible.builtin.file:
#    path: /home/docker/traefik/acme.json
#    state: touch
#    owner: docker
#    group: docker
#    mode: '0600'

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /home/docker/docker-compose.yml
    owner: docker
    group: docker
    mode: '0644'

#-----------------------NFS server for certs----------------------------------

- name: Enable NFS features for traefik LXC
  ansible.builtin.lineinfile:
    path: /etc/pve/lxc/143.conf
    line: "features: nfs=1,keyctl=1"
    state: present
  delegate_to: pve

- name: restart lxc 143
  ansible.builtin.shell: pct reboot 143
  delegate_to: pve

- name: Install nfs-kernel-server
  apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes

- name: Wait for LXC to come back
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 22
    delay: 10
    timeout: 60
  delegate_to: localhost

- name: Configure NFS ports in nfs.conf
  blockinfile:
    path: /etc/nfs.conf
    block: |
      [mountd]
      port=20048

      [statd]
      port=32765
      outgoing-port=32766

      [lockd]
      port=32768
      udp-port=32768

- name: Restart nfs-server
  systemd:
    name: nfs-server
    state: restarted
    enabled: yes

- name: Configure NFS export
  lineinfile:
    path: /etc/exports
    line: "/home/docker/dumped-certs  192.168.2.7(ro,sync,no_subtree_check,no_root_squash)"
    state: present

- name: Reload exports
  command: exportfs -ra

- name: Ensure nfs-server is started and enabled
  systemd:
    name: nfs-server
    state: started
    enabled: yes

#-----------------------Autoupdate Crowdsec hub----------------------------------

- name: Update and upgrade CrowdSec hub daily
  ansible.builtin.cron:
    name: "Crowdsec hub update/upgrade"
    minute: "0"
    hour: "3"
    job: "docker exec crowdsec cscli hub update && docker exec crowdsec cscli hub upgrade"

#-----------------------Autobackup----------------------------------

- name: Initialize traefik and crowdsec backup
  ansible.builtin.cron:
    name: "Initialize traefik and crowdsec backup"
    hour: "4"
    minute: "0"
    job: "/usr/bin/curl -s -X POST 'http://192.168.1.200:8080/generic-webhook-trigger/invoke?token=pve-webhook' -H 'Content-Type: application/json' -d '{\"event\":\"media_vm_backup\",\"node\":\"pve1\",\"host\":\"pve1.local\"}'"
    user: root
    state: present