services:
  prosody:
    image: prosodyim/prosody:13.0
    container_name: prosody
    restart: unless-stopped
    ports:
      - "5222:5222"   # XMPP client-to-server
      - "5280:5280"   # HTTP (BOSH / web / uploads если включено)
    volumes:
      - ./data:/var/lib/prosody
      - ./config:/etc/prosody
      - ./logs:/var/log/prosody
      - ./config/certs:/etc/prosody/certs
    environment:
      LOCAL_DOMAINS: xmpp.mishgun.com
      PUID: 1000
      PGID: 1000
      TZ: Europe/Moscow
    security_opt:
      - no-new-privileges:true