services:
  mariadb:
    image: mariadb:latest
    container_name: prosody-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Europe/Moscow
    volumes:
      - ./mariadb-data:/var/lib/mysql
    networks:
      - prosody-net
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  prosody:
    image: prosodyim/prosody:13.0
    container_name: prosody
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./config:/etc/prosody
      - ./data:/var/lib/prosody
      - ./certs:/etc/prosody/certs:ro
    ports:
      - "5222:5222"   # c2s (клиент-сервер)
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PUID: 1000
      PGID: 1000
      TZ: Europe/Moscow
    security_opt:
      - no-new-privileges:true
    networks:
      - prosody-net

networks:
  prosody-net:
    driver: bridge