name: local/prosody-logs
description: "Парсер Prosody"

filter: "evt.Line.Label contains 'c2s' || evt.Line.Raw contains 'Failed authentication attempt'"
onsuccess: next_stage

nodes:
  - grok:
      pattern: "Failed authentication attempt \\(.*\\) for user %{DATA:user} from IP: %{IP:source_ip}"
      apply_on: Line.Raw

statics:
  - meta: log_type
    value: prosody_failed_auth

  - meta: source_ip
    expression: "evt.Parsed.source_ip"

  - meta: target_user
    expression: "evt.Parsed.user"