type: leaky
name: local/prosody-bf
description: "Детектирование перебора паролей Prosody"
filter: "evt.Meta.log_type == 'prosody_failed_auth'"
groupby: "evt.Meta.source_ip"
capacity: 5
leakspeed: 10s
blackhole: 5m
labels:
  service: prosody
  type: brute-force
  remediation: true