template_id: 9000
template_name: debian-cloudinit-template

debian_cloud_image_url: "https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2"
debian_cloud_image_path: "/tmp/debian-13-genericcloud-amd64.qcow2"

proxmox_storage: local-lvm
proxmox_bridge: vmbr0

vm_memory: 2048
vm_cores: 2