#--------------------------Stop stack----------------------------------

- name: Stop docker compose
  ansible.builtin.shell: docker compose down -v
  args:
    chdir: /home/docker

#--------------------------Find backup----------------------------------

- name: Find latest backup
  delegate_to: localhost
  run_once: true
  ansible.builtin.shell: |
    ls -1t /srv/backups/prosody/prosody_*.tar.gz.enc 2>/dev/null | head -n 1 || true
  register: latest_backup

- name: Set fact
  set_fact:
    backup_exists: "{{ latest_backup.stdout | length > 0 }}"

#--------------------------Decrypt----------------------------------

- name: Decrypt backup locally
  ansible.builtin.shell: |
    sops -d --input-type binary --output-type binary {{ latest_backup.stdout }} > /tmp/{{ (latest_backup.stdout | basename) | regex_replace('.enc$', '') }}
  delegate_to: localhost
  when: backup_exists

#--------------------------Extract----------------------------------

- name: Remove old SQL dumps before extraction
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/home/docker/mariadb_*.sql"

- name: Extract backup
  ansible.builtin.unarchive:
    src: "/tmp/{{ (latest_backup.stdout | basename) | regex_replace('.enc$', '') }}"
    dest: /home/docker/
    remote_src: false
  when: backup_exists

#--------------------------CLEANUP CRASH LOGS--------------------------

- name: Remove corrupted tc.log to allow MariaDB start
  ansible.builtin.file:
    path: /home/docker/mariadb-data/tc.log
    state: absent

#--------------------------START DB FIRST----------------------------------

- name: Start MariaDB only
  ansible.builtin.shell: docker compose up -d mariadb
  args:
    chdir: /home/docker

- name: Wait for MariaDB to respond
  ansible.builtin.shell: |
    docker exec prosody-mariadb mariadb-admin ping -u root -p"$MYSQL_ROOT_PASSWORD"
  register: db_ping
  until: db_ping.rc == 0
  retries: 30
  delay: 5
  ignore_errors: yes

#--------------------------Restore SQL----------------------------------

- name: Find unarchived SQL dump
  ansible.builtin.shell: ls -1 /home/docker/mariadb_*.sql | head -n 1
  register: found_sql

- name: Import MariaDB dump
  ansible.builtin.shell: |
    docker exec -i prosody-mariadb \
      sh -c 'mariadb -u root -p"$MYSQL_ROOT_PASSWORD"' \
      < {{ found_sql.stdout }}

- name: Cleanup SQL dump after restore
  ansible.builtin.file:
    path: "{{ found_sql.stdout }}"
    state: absent

#--------------------------Start full stack----------------------------------

- name: Start full stack
  ansible.builtin.shell: docker compose up -d
  args:
    chdir: /home/docker

#-----------------------Add bouncer api key----------------------------------

- name: Delete existing bouncer (ignore errors)
  ansible.builtin.shell: docker exec crowdsec cscli bouncers delete prosody-firewall-bouncer
  ignore_errors: true

- name: Add bouncer
  ansible.builtin.shell: docker exec crowdsec cscli bouncers add prosody-firewall-bouncer
  register: bouncer_output

- name: Extract bouncer key
  ansible.builtin.set_fact:
    crowdsec_bouncer_key: "{{ bouncer_output.stdout_lines[2] | trim }}"

- name: Update api_key in crowdsec firewall bouncer config
  ansible.builtin.lineinfile:
    path: /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
    regexp: '^api_key:'
    line: "api_key: {{ crowdsec_bouncer_key }}"

- name: Enroll CrowdSec console
  ansible.builtin.command: >
    docker exec crowdsec cscli console enroll
    {{ lookup('pipe', 'sops -d  /var/lib/jenkins/jobs/pve/workspace/ansible/roles/traefik/config/files/enroll_secret.enc') | trim }}
  no_log: true
  ignore_errors: true

- name: Restart containers
  ansible.builtin.shell: docker compose restart
  args:
    chdir: /home/docker
  become: true
  become_method: su
  become_user: docker