---

- name: Trigger Jenkins webhook
  uri:
    url: "http://192.168.1.200:8080/generic-webhook-trigger/invoke?token=pve-webhook"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      event: terraform