---

#--------------------------User settings----------------------------------

- name: Change root password
  ansible.builtin.user:
    name: root
    password: '$6$xPh7X7pC.8NVYPQ/$flOFtvtURZugVbhpr0h0EndAb62noIGXc0NoJeRTyqbjRFRRxveNcxaLDDwp88e8.7Pc9CLektDk5fzgXy3S01'
    # python3 -c "import crypt; print(crypt.crypt('pass', crypt.mksalt(crypt.METHOD_SHA512)))"

- name: Set shell for docker user
  user:
    name: docker
    shell: /bin/bash

#--------------------------Firewall rules----------------------------------

- name: Decrypt locally
  ansible.builtin.set_fact:
    fw_content: "{{ lookup('pipe', 'sops -d /var/lib/jenkins/jobs/pve/workspace/ansible/roles/wireguard/files/126.fw.enc') }}"
  delegate_to: localhost
  no_log: true

- name: Write to pmxcfs
  ansible.builtin.shell: cat > /etc/pve/firewall/126.fw
  args:
    stdin: "{{ fw_content | replace('\r\n', '\n') }}"
  become: true
  delegate_to: pve
  no_log: true

#- name: Copy rules to target
#  ansible.builtin.copy:
#    dest: /etc/pve/firewall/126.fw
#    owner: root
#    group: www-data
#    mode: '0640'
#    content: "{{ lookup('pipe', 'sops -d /var/lib/jenkins/jobs/pve/workspace/ansible/roles/wireguard/files/126.fw.enc') }}"
#    unsafe_writes: true
#  delegate_to: pve

- name: Convert to ASCII
  ansible.builtin.shell: >
    sed -i 's/\r//' /etc/pve/firewall/126.fw
  delegate_to: pve
#--------------------------Copy wg config files----------------------------------

- name: Create wireguard_config directory
  file:
    path: /home/docker/wireguard_config
    state: directory
    owner: 1000
    group: 1000
    mode: '0700'

- name: Copy docker-compose.yml to /home/docker/
  copy:
    src: docker-compose.yml
    dest: /home/docker/docker-compose.yml
    owner: 1000
    group: 1000
    mode: '0644'

#--------------------------Unpack backup----------------------------------

- name: Decrypt backup on ansible host
  ansible.builtin.shell: >
    sops -d --input-type binary --output-type binary
    /var/lib/jenkins/jobs/pve/workspace/ansible/roles/wireguard/files/wg_config.tar.gz.enc >
    /var/lib/jenkins/jobs/pve/workspace/ansible/roles/wireguard/files/wg_config.tar.gz
  delegate_to: localhost

- name: Copy backup to target
  ansible.builtin.copy:
    src: wg_config.tar.gz
    dest: /home/docker/wg_config.tar.gz
    owner: docker
    group: docker
    mode: '0700'

- name: Remove decrypted backup on ansible host
  ansible.builtin.file:
    path: /var/lib/jenkins/jobs/pve/workspace/ansible/roles/wireguard/files/wg_config.tar.gz
    state: absent
  delegate_to: localhost

- name: Extract backup on target
  ansible.builtin.unarchive:
    src: /home/docker/wg_config.tar.gz
    dest: /home/docker
    owner: 1000
    group: 1000
    mode: '0700'
    remote_src: yes

- name: Remove backup on target
  ansible.builtin.file:
    path: /home/docker/wg_config.tar.gz
    state: absent

#--------------------------Run container----------------------------------

- name: Pull docker compose
  ansible.builtin.shell: docker compose pull
  args:
    chdir: /home/docker
  become: true
  become_method: su
  become_user: docker
  timeout: 600

- name: Start docker compose
  ansible.builtin.shell: docker compose up -d
  args:
    chdir: /home/docker
  become: true
  become_method: su
  become_user: docker