---

#-----------------------User settings----------------------------------

- name: Change root password
  ansible.builtin.user:
    name: root
    password: '$6$CBpzuPQip5YBOAPE$9KEsjowFx5czhEGtx/P8j8q3vVlvDcg5XIOh2J46fEm8uPGw9dRxNaVSJfAgVxETndudMPQHSVKiwzETl0yCw/'
    # python3 -c "import crypt; print(crypt.crypt('pass', crypt.mksalt(crypt.METHOD_SHA512)))"

- name: Set shell for docker user
  user:
    name: docker
    shell: /bin/bash

#--------------------------Firewall rules----------------------------------

- name: Decrypt locally
  ansible.builtin.set_fact:
    fw_content: "{{ lookup('pipe', 'sops -d /var/lib/jenkins/jobs/pve/workspace/ansible/roles/prosody/config/files/144.fw.enc') }}"
  delegate_to: localhost
  no_log: true

- name: Write to pmxcfs
  ansible.builtin.shell: cat > /etc/pve/firewall/144.fw
  args:
    stdin: "{{ fw_content | replace('\r\n', '\n') }}"
  become: true
  delegate_to: pve
  no_log: true

- name: Convert to ASCII
  ansible.builtin.shell: >
    sed -i 's/\r//' /etc/pve/firewall/144.fw
  delegate_to: pve

#-----------------------Install Crowdsec bouncer----------------------------------

- name: Add CrowdSec GPG key
  ansible.builtin.get_url:
    url: https://packagecloud.io/crowdsec/crowdsec/gpgkey
    dest: /usr/share/keyrings/crowdsec.gpg
    mode: '0644'

- name: Add CrowdSec repository (force bookworm)
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/crowdsec_crowdsec.list
    content: |
      deb [signed-by=/usr/share/keyrings/crowdsec.gpg] https://packagecloud.io/crowdsec/crowdsec/debian/ bookworm main

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install firewall bouncer (nftables)
  ansible.builtin.apt:
    name: crowdsec-firewall-bouncer-nftables
    state: present

#-----------------------Copy config files----------------------------------

- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: docker
    group: docker
    mode: '0755'
  loop:
    - /home/docker/data
    - /home/docker/config
    - /home/docker/certs
    - /home/docker/mariadb-data
    - /home/docker/crowdsec/config
    - /home/docker/crowdsec/data
    - /home/docker/crowdsec/parsers
    - /home/docker/crowdsec/scenarios
    - /home/docker/logs

- name: Copy prosody.cfg.lua
  copy:
    src: prosody.cfg.lua
    dest: /home/docker/config/prosody.cfg.lua
    owner: docker
    group: docker
    mode: '0644'

- name: Copy acquis.yaml
  copy:
    src: acquis.yaml
    dest: /home/docker/crowdsec/acquis.yaml
    owner: docker
    group: docker
    mode: '0644'

- name: Copy prosody CrowdSec parser
  copy:
    src: prosody-logs.yaml
    dest: /home/docker/crowdsec/parsers/prosody-logs.yaml
    owner: docker
    group: docker
    mode: '0644'

- name: Copy prosody brute-force scenario
  copy:
    src: prosody-bf.yaml
    dest: /home/docker/crowdsec/scenarios/prosody-bf.yaml
    owner: docker
    group: docker
    mode: '0644'

- name: Copy crowdsec-firewall-bouncer.yaml
  copy:
    src: crowdsec-firewall-bouncer.yaml
    dest: /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /home/docker/docker-compose.yml
    owner: docker
    group: docker
    mode: '0644'

- name: Decrypt and write .env file
  copy:
    content: "{{ lookup('pipe', 'sops -d --input-type dotenv --output-type dotenv /var/lib/jenkins/jobs/pve/workspace/ansible/roles/prosody/config/files/.env.enc') }}"
    dest: /home/docker/.env
    owner: docker
    group: docker
    mode: '0400'
#--------------------------Clone/update prosody community modules----------------------------------

- name: Ensure mercurial is installed
  ansible.builtin.apt:
    name: mercurial
    state: present

- name: Check if community-modules directory exists
  ansible.builtin.stat:
    path: /home/docker/community-modules/.hg
  register: community_modules_dir

- name: Clone prosody community modules
  ansible.builtin.shell: |
    hg clone https://hg.prosody.im/prosody-modules/ /home/docker/community-modules
  args:
    creates: /home/docker/community-modules/.hg
  become: true
  become_method: su
  become_user: docker
  when: not community_modules_dir.stat.exists

- name: Update prosody community modules
  ansible.builtin.shell: |
    hg pull -u -R /home/docker/community-modules
  become: true
  become_method: su
  become_user: docker
  when: community_modules_dir.stat.exists

#-----------------------Add mount point----------------------------------

- name: Add mount point to container 143
  ansible.builtin.command: >
    pct set 144 -mp0 /srv/certs/dumped-certs/,mp=/home/docker/certs
  delegate_to: pve

#-----------------------Autobackup----------------------------------

- name: Initialize prosody backup
  ansible.builtin.cron:
    name: "Initialize prosody backup"
    hour: "4"
    minute: "30"
    job: >-
      curl -X POST
      "http://192.168.2.200:8080/generic-webhook-trigger/invoke?token=pve-webhook"
      -H "Content-Type: application/json"
      -d '{"event":"prosody-backup","node":"pve1","host":"pve1.local"}'
      >> /var/log/traefik-backup-webhook.log 2>&1
    state: "{{ state | default('present') }}"