x-common-keys: &common-keys
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/Moscow

services:
  prowlarr:
    <<: *common-keys
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    ports:
      - "9696:9696"
    volumes:
      - ./prowlarr_config:/config

  sonarr-anime:
    <<: *common-keys
    container_name: sonarr-anime
    image: ghcr.io/hotio/sonarr:latest
    ports:
      - "8989:8989"
    volumes:
      - ./sonarr_anime_config:/config
      - /media:/data

  sonarr-series:
    <<: *common-keys
    container_name: sonarr-series
    image: ghcr.io/hotio/sonarr:latest
    ports:
      - "8990:8990"
    volumes:
      - ./sonarr_series_config:/config
      - /media:/data

  radarr:
    <<: *common-keys
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    ports:
      - "7878:7878"
    volumes:
      - ./radarr_config:/config
      - /media:/data

  bazarr:
    <<: *common-keys
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=6767/tcp
    volumes:
      - ./bazarr_config:/config
      - /media:/data


  qbittorrent:
    <<: *common-keys
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:latest
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent_config:/config
      - /media:/data

  seerr:
    <<: *common-keys
    container_name: seerr
    image: ghcr.io/hotio/seerr:latest
    ports:
      - "5055:5055"
    volumes:
      - ./seerr_config:/config

  jellyfin:
    <<: *common-keys
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin:latest
    volumes:
      - ./jellyfin_config:/config
      - /media/library:/media:ro #read-only
    ports:
      - "8096:8096"

  emby:
    <<: *common-keys
    container_name: embyserver
    image: emby/embyserver
    volumes:
      - ./emby_config:/config # Configuration directory
      - /media/library:/media:ro # Media directory
    ports:
      - "8096:8096" # HTTP port

  samba:
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    network_mode: host
    volumes:
      - /media:/media
    command: >
      -u "user;strongpassword"
      -s "media;/media;yes;no;no;user"

networks:
  default:
    name: arr_network
