http:
  routers:
    prosody-upload:
      entryPoints:
        - websecure
      rule: "Host(`upload.mishgun.com`)"
      service: prosody-http
      middlewares:
        - crowdsec@file
      tls: {}

    prosody-web:
      entryPoints:
        - websecure
      rule: "Host(`xmpp.mishgun.com`)"
      service: prosody-http
      middlewares:
        - crowdsec@file
      tls: {}

  services:
    prosody-http:
      loadBalancer:
        servers:
          - url: "http://192.168.4.4:5280"
        passHostHeader: true