---

http:
  routers:
    # Проброс http-01 challenge и BOSH/WebSocket
    xmpp-http:
      entryPoints:
        - web
      rule: "Host(`xmpp.mishgun.com`)"
      service: prosody-http

  services:
    prosody-http:
      loadBalancer:
        servers:
          - url: "http://192.168.4.4:5280"

tcp:
  routers:
    prosody-c2s:
      entryPoints:
        - xmpp
      rule: "HostSNI(`*`)"
      service: prosody-c2s
      tls:
        passthrough: true

  services:
    prosody-c2s:
      loadBalancer:
        servers:
          - address: "192.168.4.4:5222"