---

tcp:
  routers:
    prosody-c2s:
      entryPoints:
        - xmpp
      rule: "HostSNI(`*`)"
      service: prosody-c2s
      tls:
        passthrough: true

  services:
    prosody-c2s:
      loadBalancer:
        servers:
          - address: "192.168.4.4:5222"