#------------------------------------------Stop stack safely------------------------------------------

- name: Stop docker compose (clean shutdown)
  ansible.builtin.shell: docker compose down -v
  args:
    chdir: /home/docker

#------------------------------------------Generate timestamp------------------------------------------

- name: Generate timestamp
  ansible.builtin.set_fact:
    backup_time: "{{ lookup('pipe', 'date +%d_%m_%Y_%H_%M') }}"

#------------------------------------------Create backup dir------------------------------------------

- name: Create backup directory on control
  ansible.builtin.file:
    path: /srv/backups/prosody
    state: directory
    mode: '0755'
  delegate_to: localhost

#------------------------------------------MYSQL DUMP------------------------------------------

- name: Dump MariaDB (safe logical backup)
  ansible.builtin.shell: |
    docker exec prosody-mariadb mysqldump \
      --all-databases \
      --single-transaction \
      --routines \
      --triggers \
      > /home/docker/mariadb_{{ backup_time }}.sql
  become: true

#------------------------------------------Archive only safe data------------------------------------------

- name: Archive Prosody (NO raw mariadb-data anymore)
  become: true
  ansible.builtin.archive:
    path:
      - /home/docker/crowdsec/data
      - /home/docker/mariadb_{{ backup_time }}.sql
    dest: "/home/docker/prosody_{{ backup_time }}.tar.gz"
    format: gz

#------------------------------------------Encrypt------------------------------------------

- name: Encrypt archive
  ansible.builtin.shell: >
    sops -e --input-type binary --output-type binary prosody_{{ backup_time }}.tar.gz > prosody_{{ backup_time }}.tar.gz.enc
  args:
    chdir: /home/docker

#------------------------------------------Fetch------------------------------------------

- name: Fetch encrypted backup
  ansible.builtin.fetch:
    src: "/home/docker/prosody_{{ backup_time }}.tar.gz.enc"
    dest: "/srv/backups/prosody/"
    flat: true

#------------------------------------------Cleanup------------------------------------------

- name: Cleanup remote files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/home/docker/prosody_{{ backup_time }}.tar.gz"
    - "/home/docker/prosody_{{ backup_time }}.tar.gz.enc"
    - "/home/docker/mariadb_{{ backup_time }}.sql"

#------------------------------------------Start stack------------------------------------------

- name: Start docker compose
  ansible.builtin.shell: docker compose up -d
  args:
    chdir: /home/docker