---

- name: Prosody VM config
  hosts: prosody_vm
  remote_user: root
  gather_facts: true
  roles:
    - common/basic
    - common/docker
    - common/monitoring
    #    - prosody/backup
    - prosody/config
#    - prosody/restore