---

- name: PVE config
  hosts: pve
  remote_user: root
  gather_facts: false
  vars:
    ansible_password: "12345678"
    ansible_pipelining: false
  roles:
#    - common/update_known_hosts
    - pve/config_soft
    - pve/config_hard_test
    - pve/firstboot_clean
    - pve/get_api_token