---
- name: Run selected roles
  hosts: "{{ target_hosts }}"
  become: true

  tasks:
    - name: Show selected roles
      ansible.builtin.debug:
        msg:
          - "ROLE={{ role_name }}"
          - "TARGET={{ target_hosts }}"

    - name: Run selected roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ role_name.split(';') | map('trim') | list }}"
      loop_control:
        label: "{{ item }}"