---
- name: Run selected roles
  hosts: "{{ target_hosts }}"
  become: true

  tasks:
    - name: Run roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ role_name.split(',') | map('trim') | list }}"