---
- name: Install Node Exporter
  block:
    - name: Install Node Exporter
      block:
        - name: Install Node Exporter (Debian/Ubuntu)
          ansible.builtin.apt:
            name: prometheus-node-exporter
            state: present
            update_cache: true
          when: ansible_facts["os_family"] == "Debian"

        - name: Install Node Exporter (RedHat/CentOS)
          ansible.builtin.yum:
            name: node_exporter
            state: present
          when: ansible_facts["os_family"] == "RedHat"

    - name: Ensure Node Exporter is started and enabled
      ansible.builtin.service:
        name: "{{ 'prometheus-node-exporter' if ansible_facts['os_family'] == 'Debian' else 'node_exporter' }}"
        state: started
        enabled: true

  when: node_exporter_enabled

- name: Configure Node Exporter (Optional - if custom port is needed)
  # Если порт по умолчанию 9100 подходит, этот блок можно упростить
  # Но на будущее удобно иметь возможность менять порт через vars
  debug:
    msg: "Node Exporter is running on port {{ node_exporter_port }}"
