services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Moscow
      ACME_DNS_API_BASE: http://acme-dns:8080
      ACME_DNS_STORAGE_PATH: /acme-dns/acme-dns.json
    ports:
      - "80:80"
      - "443:443"
      - "5222:5222"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/cs_secret:/etc/traefik/cs_secret:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - ./certs/traefik/acme.json:/etc/traefik/acme.json
      - ./traefik/logs:/var/log/traefik
      - ./acme-dns:/acme-dns
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    depends_on:
      - crowdsec
      - acme-dns

  acme-dns:
    image: joohoi/acme-dns:v1.0
    container_name: acme-dns
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "127.0.0.1:8080:8080"
    volumes:
      - ./acme-dns/config:/etc/acme-dns
      - ./acme-dns/data:/var/lib/acme-dns
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Moscow
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Moscow
      COLLECTIONS: crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/base-http-scenarios crowdsecurity/linux
    volumes:
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml:ro
      - ./crowdsec/config:/etc/crowdsec/
      - ./traefik/logs:/var/log/traefik:ro
      - ./crowdsec/data:/var/lib/crowdsec/data
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true

  traefik-certs-dumper:
    image: ldez/traefik-certs-dumper:latest
    container_name: traefik-certs-dumper
    restart: unless-stopped
    command:
      - file
      - --watch
      - --source
      - /acme.json
      - --dest
      - /dumped-certs
      - --domain-subdir
      - --key-ext=.pem
      - --crt-ext=.pem
      - --version
      - v2
      - --post-hook
      - "chown -R 1000:1000 /dumped-certs"
    volumes:
      - ./certs/traefik/acme.json:/acme.json:ro
      - ./certs/dumped-certs:/dumped-certs
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Moscow
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    name: proxy