services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Moscow
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/cs_secret:/etc/traefik/cs_secret:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - ./traefik/acme.json:/etc/traefik/acme.json
      - ./traefik/logs:/var/log/traefik
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    depends_on:
      crowdsec:
        condition: service_started

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Moscow
      COLLECTIONS: crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/base-http-scenarios crowdsecurity/linux
    volumes:
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml:ro
      - ./crowdsec/config:/etc/crowdsec/
      - ./traefik/logs:/var/log/traefik:ro
      - ./crowdsec/data:/var/lib/crowdsec/data
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    name: proxy