[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/app/qBittorrent/data/logs

[BitTorrent]
Session\AlternativeGlobalDLSpeedLimit=30000
Session\AlternativeGlobalUPSpeedLimit=30000
Session\BandwidthSchedulerEnabled=true
Session\DefaultSavePath=/data/torrents
Session\DisableAutoTMMByDefault=false
Session\DisableAutoTMMTriggers\CategorySavePathChanged=false
Session\DisableAutoTMMTriggers\DefaultSavePathChanged=false
Session\ExcludedFileNames=
Session\Port=45321
Session\QueueingSystemEnabled=false
Session\SSL\Port=35566
Session\UseAlternativeGlobalSpeedLimit=true

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Preferences]
General\Locale=en
MailNotification\req_auth=true
Scheduler\end_time=@Variant(\0\0\0\xf\0\0\0\0)
WebUI\AlternativeUIEnabled=true
WebUI\AuthSubnetWhitelist=192.168.1.149/32, 192.168.1.129/32
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\Password_PBKDF2="@ByteArray(/GddWpxqCv1++eFf6gog5Q==:hXV1kpkvVedpWGZSQpXRnolPugwTx9OWiRcCX7Migbr/hHKO5zGnYT8fsGZHt4hYI6GBJyBbnbmNaOPeJQo8cQ==)"
WebUI\RootFolder=/VueTorrent

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
