when:
  - event: push
    branch: main
    path:
      include:
        - ansible/pvpgn_config.yml
        - ansible/roles/pvpgn/config/**

  - event: manual

steps:
  deploy:
    image: alpine/ansible:latest

    environment:
      SSH_KEY:
        from_secret: ssh_key

    commands:
commands:
  - mkdir -p ~/.ssh
  - printf '%s\n' "$SSH_KEY" > ~/.ssh/id_ed25519
  - chmod 600 ~/.ssh/id_ed25519
  - export ANSIBLE_CONFIG=ansible/ansible.cfg
  - ansible-inventory -i ansible/hosts_prod --graph
  - ansible-playbook -i ansible/hosts_prod ansible/pvpgn_config.yml