when:
  - event: push
    branch: main

  - event: manual
    evaluate: 'PIPELINE == "full"'

steps:
  deploy:
    image: alpine/ansible:latest

    environment:
      SSH_KEY:
        from_secret: ssh_key

    commands:
      - |

        apk add --no-cache sops

        mkdir -p ~/.ssh
        printf '%s\n' "$SSH_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

        export ANSIBLE_CONFIG=ansible/ansible.cfg

        ansible-playbook \
          -i ansible/hosts_prod \
          ansible/pvpgn_config.yml