---

#--------------------------User settings----------------------------------

- name: Change root password
  ansible.builtin.user:
    name: root
    password: '$6$5XSvZTLtQZxtQuWA$INm8v41m5StolnQICgNIyBAjmXWY0KcYGnQ4mTeU26wYCsbbfQGANWYlUP7F7ikmtZKvWOVf7TvXM6Slwc5Oc/'
    # python3 -c "import crypt; print(crypt.crypt('pass', crypt.mksalt(crypt.METHOD_SHA512)))"

- name: Set shell for docker user
  user:
    name: docker
    shell: /bin/bash

#--------------------------Firewall rules----------------------------------

- name: Decrypt locally
  ansible.builtin.set_fact:
    fw_content: "{{ lookup('pipe', 'sops -d /var/lib/jenkins/jobs/pve/workspace/ansible/roles/pvpgn/config/files/145.fw.enc') }}"
  delegate_to: localhost
  no_log: true

- name: Write to pmxcfs
  ansible.builtin.shell: cat > /etc/pve/firewall/145.fw
  args:
    stdin: "{{ fw_content | replace('\r\n', '\n') }}"
  become: true
  delegate_to: pve
  no_log: true


- name: Convert to ASCII
  ansible.builtin.shell: >
    sed -i 's/\r//' /etc/pve/firewall/145.fw
  delegate_to: pve

#--------------------------Copy PVPGN config files----------------------------------

- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: 1001
    group: 1001
    mode: '0755'
  loop:
    - /home/docker/pvpgn_conf
    - /home/docker/pvpgn_var/files
    - /home/docker/pvpgn_var/status
    - /home/docker/pvpgn_var/ladders
    - /home/docker/db

- name: Copy bnetd.conf
  copy:
    src: bnetd.conf
    dest: /home/docker/pvpgn_conf/bnetd.conf
    owner: 1001
    group: 1001
    mode: '0644'

- name: Copy support files
  copy:
    src: support/
    dest: /home/docker/pvpgn_var/files/
    owner: 1001
    group: 1001
    mode: '0644'

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /home/docker/docker-compose.yml
    owner: docker
    group: docker
    mode: '0644'

#-----------------------Autobackup----------------------------------

- name: Add cron task for PVPGN backup
  ansible.builtin.cron:
    name: "Initialize PVPGN backup"
    hour: "4"
    minute: "50"
    job: >-
      curl -X POST
      "http://192.168.2.200:8080/generic-webhook-trigger/invoke?token=pve-webhook"
      -H "Content-Type: application/json"
      -d '{"event":"pvpgn-backup","node":"pve1","host":"pve1.local"}'
      >> /var/log/traefik-backup-webhook.log 2>&1
    state: "{{ state | default('present') }}"