---

#-----------------------Set timezone----------------------------------

- name: Set Europe/Moscow timezone
  ansible.builtin.shell: timedatectl set-timezone Europe/Moscow

#-----------------------Change sshd config----------------------------------

- name: Change sshd config
  ansible.builtin.copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config

- name: Disable and stop ssh.socket
  systemd:
    name: ssh.socket
    enabled: false
    state: stopped

- name: Restart ssh
  systemd:
    name: ssh
    state: restarted
    enabled: true

- name: Wait for SSH to come back
  wait_for:
    port: 22
    delay: 2
    timeout: 30

#-----------------------Update and upgrade----------------------------------

- name: Update repo and upgrade packages
  ansible.builtin.apt:
    name: '*'
    state: latest
    update_cache: yes

#-----------------------Install fail2ban----------------------------------

#- name: Install fail2ban
#  ansible.builtin.apt:
#    name: fail2ban
#    state: latest
#
#- name: Add fail2ban config file
#  ansible.builtin.copy:
#    src: jail.local
#    dest: /etc/fail2ban/jail.local
#
#- name: Restart fail2ban service
#  ansible.builtin.systemd_service:
#    state: restarted
#    name: fail2ban

#-----------------------Install packages----------------------------------

- name: Install apt packages
  ansible.builtin.apt:
    name:
      - neovim
      - cron
      - zip
      - unzip
    state: latest

- name: Install sops binary
  get_url:
    url: https://github.com/getsops/sops/releases/download/v3.12.2/sops-v3.12.2.linux.amd64
    dest: /usr/local/bin/sops
    mode: '0755'
    owner: root
    group: root

#-----------------------Copy .bashrc----------------------------------

- name: Copy .bashrc
  ansible.builtin.copy:
    src: .bashrc
    dest: /root/.bashrc

#-----------------------Scheduled update----------------------------------

- name: System update via cron
  cron:
    name: "APT update and cleanup"
    minute: "20"
    hour: "6"
    job: >
      apt update &&
      apt upgrade -y &&
      apt autoremove -y &&
      apt autoclean -y

#-----------------------Reboot----------------------------------
#
#- name: Reboot
#  ansible.builtin.reboot: